networks:
  internal-pod:
    internal: true
  external-pod:
    internal: false

volumes:
  dolibarr-custom:
  dolibarr-docs:
  mysql-data:

services:
  dolibarr:
    image: dolibarr
    environment:
      DOLI_DB_HOST: "mysql"
      DOLI_DB_HOST_PORT: "3306"
      DOLI_DB_USER: "dolibarr"
      DOLI_DB_PASSWORD: "dolipass"
      DOLI_DB_NAME: "dolibarr"
      DOLI_ADMIN_LOGIN: "admin"
      DOLI_ADMIN_PASSWORD: "dolibarr"
    ports:
      - 8888:80
    volumes:
      - dolibarr-docs:/var/www/documents
      - dolibarr-custom:/var/www/html/custom
    networks:
      - internal-pod
      - external-pod

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "dolibarr"
      MYSQL_USER: "dolibarr"
      MYSQL_PASSWORD: "dolipass"
      MYSQL_ROOT_PASSWORD: "mysupersupersecretpasswordforrootuser"

    ports:
      - 3312:3306
    volumes:
      - mysql-data:/var/lib/mysql3
    networks:
      - internal-pod