name: dolibarr-21

on:
  push:
    branches: [ release ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: dolibarr:21

      - name: Save Docker image
        run: |
          mkdir -p ./deploy
          docker save dolibarr:21 | gzip > ./deploy/dolibarr-image.tar.gz

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SOURCE: "deploy/"
          TARGET: "/tmp/dolibarr-deploy"

      - name: Load and run Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd
            cd dockerfiles
            source ~/.init.sh
            docker compose stop web
            docker compose rm -f web
            gunzip -c /tmp/dolibarr-deploy/dolibarr-image.tar.gz | docker load
            docker compose up -d web
            ls -l /tmp/dolibarr-deploy
            rm -rf /tmp/dolibarr-deploy