name: My backend host

on:
    push:
      branches: [ main ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: 'Setup QEMU'
          uses: docker/setup-qemu-action@v1
        - name: 'Setup Docker Buildx'
          uses: docker/setup-buildx-action@v1
        - name: 'Login to DockerHub'
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: 'Build and push'
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: developersongyam/dolibarr:21
        
        # - name: Deploy using ssh
        #   uses: appleboy/ssh-action@master
        #   with:
        #     host: ${{ secrets.SSH_HOST }}
        #     username: ${{ secrets.SSH_USERNAME }}
        #     key: ${{ secrets.SSH_PRIVATE_KEY }}
        #     port: 22
        #     script: |
        #       source ~/.bashrc
        #       cd dockefiles

        #       docker compose stop appweb
        #       docker compose rm -f appweb
        #       docker rmi -f developersongyam/songyam-app-web:0.0.1
        #       docker compose up -d appweb